<?php
    $news = [
        [
            'id'=> 1,
            'title'=> "EGLISE MES: COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 2,
            'title'=> "VISITE DE LA DELEGATION DE WHH AU BUREAU FARP",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 3,
            'title'=> "FARP EST DÉJÀ REPRÉSENTÉ SUR LE WEB (SUR INTERNET)",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 4,
            'title'=> "COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 5,
            'title'=> "EGLISE MES: COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 6,
            'title'=> "EGLISE MES: COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 7,
            'title'=> "EGLISE MES: COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
        [
            'id'=> 8,
            'title'=> "EGLISE MES: COMMEMORATION DU JUBILE D'ARGENT",
            'content'=>
              "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quasi dolor voluptatem voluptates esse et, eius minus, laboriosam delectus eum mollitia dolorem animi magnam soluta tempora. Quod ducimus corporis unde suscipit quas ex, nostrum placeat aspernatur inventore, odit optio non mollitia illum ea numquam ad iure quidem nihil maiores doloribus. Cupiditate, quod excepturi pariatur nisi voluptatibus obcaecati odio ducimus, temporibus hic qui illo quaerat minus quae maxime ratione vel eaque quasi. Alias architecto accusantium est dolorum explicabo pariatur! Fugiat temporibus quam optio reiciendis esse ad voluptates, ut inventore! Similique necessitatibus voluptatum officiis aspernatur animi, atque modi explicabo provident libero minima quia consequatur in voluptatibus cupiditate culpa harum pariatur dolorem itaque laudantium esse debitis vel. Aperiam ea eum incidunt assumenda quia eaque sapiente sit. Nihil cupiditate, iure explicabo deserunt omnis non. Numquam ullam rem molestias pariatur libero dolorem, aliquam at ea, rerum, facere repellat totam cupiditate saepe architecto eos nisi! Provident quas praesentium labore. Facere natus quae eos alias? Aut doloremque soluta dolore, explicabo aliquam quod et aspernatur quaerat, repudiandae veniam earum placeat nulla impedit! Error quos beatae, alias ad molestiae animi consequatur dolore maiores porro, amet consectetur voluptate, facilis aliquam totam! Aspernatur pariatur tenetur recusandae non voluptatum inventore optio voluptas accusantium? Quibusdam, cupiditate accusamus earum dolores voluptas ipsa quaerat minus neque deserunt nobis, veritatis consequuntur corrupti? Perspiciatis, quaerat. Unde exercitationem eius nisi totam modi optio quibusdam? Molestiae ratione cum itaque quaerat minus sed reiciendis suscipit animi, impedit quidem id vitae magni facilis culpa iusto eius natus aperiam vel expedita. Enim?",
            'img'=> "../assets/img/news/evangeline-shaw-ysbTWw4hrG4-unsplash-small.jpg",
            'slug'=> "Lorem-ipsum-dolor-sit-amet-consectetur",
        ],
    ];

    $videosLink = [
        [
            'id' => 1,
            'link' => 'https://www.youtube.com/embed/HZciKfVkY-c',
        ],
        [
            'id' => 2,
            'link' => 'https://www.youtube.com/watch?v=vBxVWn9i8pM',
        ],
        [
            'id' => 3,
            'link' => 'https://www.youtube.com/watch?v=0UR6n1JAOaI',
        ],
        [
            'id' => 4,
            'link' => 'https://www.youtube.com/watch?v=ka2ekjhU2VM',
        ],
        [
            'id' => 5,
            'link' => 'https://www.youtube.com/watch?v=868VHYolYjo',
        ],
    ];